from setuptools import setup
import os
import sys
import subprocess

version_py = os.path.join(os.path.dirname(__file__), 'dbxsh', 'version.py')
try:
    version_git = subprocess.check_output(["git", "describe", "--tags"]).rstrip()
except:
    with open(version_py, 'r') as fh:
        version_git = open(version_py).read().strip().split('=')[-1].replace('"','')

version_msg = "# Do not edit this file, pipeline versioning is governed by git tags"
with open(version_py, 'w') as fh:
    fh.write(version_msg + os.linesep + "__version__='" + version_git + "'") 

setup(
    name='dbxsh',
    version="{ver}".format(ver=version_git),
    author='Panayotis Vryonis',
    author_email='vrypan@gmail.com',
    package_dir={'dbxsh': 'dbxsh'},
    packages=['dbxsh',],
    scripts=['bin/dbxsh'],
    include_package_data=True,
    url='http://www.vrypan.net/',
    license='MIT-LICENSE.txt',
    description='Dropbox commandline tools (unofficial).',
    long_description=open('README.rst').read(),
    install_requires=[
        "docopt",
        "dropbox",
    ],
    dependency_links = ['https://github.com/dropbox/dropbox-sdk-python/tarball/master'],
    classifiers=[
        'Development Status :: 4 - Beta',
        'Environment :: Console',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 2.6',
        'Programming Language :: Python :: 2.7',
        'Topic :: Internet :: WWW/HTTP',
    ],

)
